"""
Pydantic models for VPC and BMC components.
"""

from .common import (
    ResponseFormat,
    BusinessStage,
    JobType,
    GainType,
    ChannelPhase,
    RelationshipType,
    ResourceType,
    ActivityType,
    RevenueType,
    PricingMechanism,
    CostType,
    QualityScore,
    Recommendation,
    ValidationResult,
)
from .vpc import (
    CustomerJob,
    CustomerPain,
    CustomerGain,
    ProductService,
    PainReliever,
    GainCreator,
    CustomerProfile,
    ValueMap,
    VPCInput,
    VPCOutput,
)
from .bmc import (
    CustomerSegment,
    ValueProposition,
    Channel,
    CustomerRelationship,
    RevenueStream,
    KeyResource,
    KeyActivity,
    KeyPartnership,
    CostItem,
    BMCInput,
    BMCOutput,
)

__all__ = [
    # Common
    "ResponseFormat",
    "BusinessStage",
    "JobType",
    "GainType",
    "ChannelPhase",
    "RelationshipType",
    "ResourceType",
    "ActivityType",
    "RevenueType",
    "PricingMechanism",
    "CostType",
    "QualityScore",
    "Recommendation",
    "ValidationResult",
    # VPC
    "CustomerJob",
    "CustomerPain",
    "CustomerGain",
    "ProductService",
    "PainReliever",
    "GainCreator",
    "CustomerProfile",
    "ValueMap",
    "VPCInput",
    "VPCOutput",
    # BMC
    "CustomerSegment",
    "ValueProposition",
    "Channel",
    "CustomerRelationship",
    "RevenueStream",
    "KeyResource",
    "KeyActivity",
    "KeyPartnership",
    "CostItem",
    "BMCInput",
    "BMCOutput",
]
